name: Node package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        node-version: [ '14', '15', '16' ]
        prefix: [ "qaseio", "qase-cypress", "qase-cucumberjs", "qase-newman", "qase-testcafe", "qase-jest", "qase-playwright", "qase-js-common" ]
    name: Project ${{ matrix.prefix }} - Node ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./${{ matrix.prefix }}
      run: npm install
    - working-directory: ./${{ matrix.prefix }}
      run: npm run lint
    - working-directory: ./${{ matrix.prefix }}
      run: npm run test
  build-n-publish:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      max-parallel: 5
      matrix:
        prefix: [ "qaseio", "qase-cypress", "qase-cucumberjs", "qase-newman", "qase-testcafe", "qase-jest", "qase-playwright", "qase-js-common" ]
    if: startsWith(github.event.ref, 'refs/tags')
    name: Publish ${{ matrix.prefix }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      if: contains(github.event.ref, matrix.prefix)
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm install
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm run build
    - if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
